apiVersion: apps/v1
kind: Deployment
metadata:
  name: billpunch
  labels:
    app: billpunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billpunch
  template:
    metadata:
      labels:
        app: billpunch
    spec:
      containers:
      - name: billpunch
        image: janmenjaya/billpunch
        ports:
        - containerPort: 30004  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: billpunch
  name: billpunch
  namespace: default
spec:
  clusterIP: 10.110.193.63
  clusterIPs:
  - 10.110.193.63
  internalTrafficPolicy: Cluster
  ports:
  - port: 30004
    protocol: TCP
    targetPort: 30004
  selector:
    app: billpunch
  sessionAffinity: None
  type: ClusterIP
