apiVersion: apps/v1
kind: Deployment
metadata:
  name: billpunch
  labels:
    app: billpunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billpunch
  template:
    metadata:
      labels:
        app: billpunch
    spec:
      containers:
      - name: billpunch
        image: janmenjaya/billpunch
        ports:
        - containerPort: 30004  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  labels:
    app: billpunch
  name: billpunch
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32097
    port: 30004
    protocol: TCP
    targetPort: 30004
  selector:
    app: billpunch
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.56.244
